### ISSUE TITLE
Crashed on Startup

### ISSUE THREAD

**Issue by GuffeTheGreat** [Shadows-of-Fire/Shadows-of-Greg#15]
WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.12.2-4.2.7.jar)
  CreativePatchingLoader (CreativeCore_v1.9.41_mc1.12.2.jar)
  ColytraLoadingPlugin (colytra-1.12.2-1.1.1.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-0.3.3.22.jar)
  TheBetweenlandsLoadingPlugin (TheBetweenlands-3.4.4-core.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  AstralCore (astralsorcery-1.12.2-1.10.11.jar)
  Wizardry Plugin (wizardry-0.9.9.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.1.jar)
  Botania Tweaks Core (botaniatweaks-1.8.4.jar)
  LoadingPlugin (Bloodmoon-MC1.12.2-1.5.3 (1).jar)
  MicdoodlePlugin (MicdoodleCore-1.12.2-4.0.1.181.jar)
  LoadingPlugin (Quark-r1.5-146 (2).jar)
  LibrarianLib Plugin (librarianlib-1.12.2-4.15.jar)
  JEIDLoadingPlugin (JustEnoughIDs-1.0.2-26.jar)
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b162.jar)
  llibrary (llibrary-core-1.0.10-1.12.2.jar)
  HCASM (HammerCore-1.12.2-2.0.4.2.jar)
  IvToolkit (IvToolkit-1.3.3-1.12 (1).jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1 (1).jar)
  Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.3-1.12.2.jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.12.2-1.5.0-136-universal.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.45.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 4/2/19 8:46 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Shadows of Greg (gtadditions)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at gregicadditions.recipes.GARecipeAddition.generatedRecipes(GARecipeAddition.java:1399)
	at gregicadditions.GregicAdditions.postInit(GregicAdditions.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:749)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Shadows-of-Fire** [comment]
Not enough information, GTCE and SoG versions must be stated
