### ISSUE TITLE
Possible issue with upcoming GregTech CE Master

### ISSUE THREAD

**Issue by cptroot** [Shadows-of-Fire/Shadows-of-Greg#36]
I tried to update my Omnifactory 1.2.1 pack to use GregTech CE master today, and I got the following stacktraces in my startup log. In addition, all of the recipes for things like `macerate magnetite` were missing when the game loaded. I'm not sure what the issue is, but it seems like there might be an API change in recent versions of GregTech CE. This issue doesn't happen with `gregtech-1.12.2-1.8.4.419`. Let me know if I can provide more issue to help debugging.

```
[13:03:15] [Client thread/ERROR]: Tried to register recipe, silicone_rubber_ring, with duplicate key. Recipe: "k", "P", "P", "1xitem.meta_item@12391"
[13:03:15] [Client thread/ERROR]: Stacktrace:
java.lang.IllegalArgumentException: null
	at gregtech.api.recipes.ModHandler.validateRecipe(ModHandler.java:337) [ModHandler.class:?]
	at gregtech.api.recipes.ModHandler.addShapedRecipe(ModHandler.java:280) [ModHandler.class:?]
	at gregicadditions.recipes.GARecipeAddition.init(GARecipeAddition.java:241) [GARecipeAddition.class:?]
	at gregicadditions.GregicAdditions.registerRecipes(GregicAdditions.java:73) [GregicAdditions.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1246_GregicAdditions_registerRecipes_Register.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) [EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857) [GameData.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:629) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
[13:03:15] [Client thread/ERROR]: Tried to register recipe, styrene_rubber_ring, with duplicate key. Recipe: "k", "P", "P", "1xitem.meta_item@12398"
[13:03:15] [Client thread/ERROR]: Stacktrace:
java.lang.IllegalArgumentException: null
	at gregtech.api.recipes.ModHandler.validateRecipe(ModHandler.java:337) [ModHandler.class:?]
	at gregtech.api.recipes.ModHandler.addShapedRecipe(ModHandler.java:280) [ModHandler.class:?]
	at gregicadditions.recipes.GARecipeAddition.init(GARecipeAddition.java:242) [GARecipeAddition.class:?]
	at gregicadditions.GregicAdditions.registerRecipes(GregicAdditions.java:73) [GregicAdditions.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1246_GregicAdditions_registerRecipes_Register.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) [EventBus$1.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:857) [GameData.class:?]
	at net.minecraftforge.common.crafting.CraftingHelper.loadRecipes(CraftingHelper.java:629) [CraftingHelper.class:?]
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336) [FMLClientHandler.class:?]
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535) [bib.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51]
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
```

**Comment by EconBrony** [comment]
i am getting a similar issue, the strange thing is it won't allow me to launch a server with it, but I can launch it on the client side

**Comment by Shadows-of-Fire** [comment]
fbc668e
